# Generated by Django 5.1.1 on 2025-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_delete_message_utilisateur_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_club_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_president',
            field=models.BooleanField(default=False),
        ),
    ]
