# Generated by Django 5.1.1 on 2025-04-29 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_utilisateur_is_admin_utilisateur_is_club_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs_logos/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
