# Generated by Django 5.2 on 2025-05-13 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_club_logo_alter_club_membres'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='demandes_membres',
            field=models.ManyToManyField(blank=True, related_name='clubs_demandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
