# Generated by Django 5.2 on 2025-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_club_demandes_membres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='demandes_membres',
        ),
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
