# Generated by Django 5.2 on 2025-05-16 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_remove_club_demandes_membres_club_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='demandes_membres',
            field=models.ManyToManyField(related_name='demandes_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evenement',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='membres',
            field=models.ManyToManyField(related_name='clubs_membres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.club'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(related_name='evenements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
