# Generated by Django 5.2 on 2025-05-16 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_club_demandes_membres_evenement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='demandes_membres',
        ),
        migrations.AddField(
            model_name='evenement',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='utilisateurs.club'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Valide')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
