# Generated by Django 5.2 on 2025-05-17 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_remove_club_demandes_membres_evenement_max_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='evenement',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/logos/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clubs_responsables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='evenements_participes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('membre', 'Membre'), ('responsable', 'Responsable')], default='membre', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='membres',
            field=models.ManyToManyField(related_name='clubs', through='utilisateurs.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
