# Generated by Django 5.2 on 2025-05-17 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_remove_club_is_active_remove_evenement_max_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='status',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='createur',
        ),
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs_logos/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='membres',
            field=models.ManyToManyField(related_name='clubs_membres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Valide')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
